name: example_flutter
description: An example project for flutter-desktop-embedding.

version: 0.1.0

environment:
  sdk: '>=2.0.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.10.2-pre.54'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  provider: ^4.0.2
  flutter_bloc: ^3.1.0
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  http: ^0.12.0+4
  recase: ^3.0.0
  flutter_spinkit: "^2.1.0"


dev_dependencies:
  flutter_test:
    sdk: flutter

  hydrated_bloc: ^3.0.0
  equatable: ^1.0.2
  json_annotation: ^3.0.1
  build_runner:
  json_serializable: ^3.2.5
  flutter_redux: ^0.6.0
  redux: ^4.0.0
  redux_thunk: ^0.3.0

flutter:
  uses-material-design: true

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
